package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GeneralEstado generated by hbm2java
 */
public class GeneralEstado  implements java.io.Serializable {


     private Integer estadoId;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;
     private Set organizacionDetordentrabajos = new HashSet(0);
     private Set organizacionOrdenservicios = new HashSet(0);
     private Set productoResponsableactivos = new HashSet(0);
     private Set productoProductoatributos = new HashSet(0);
     private Set productoRelacionproductos = new HashSet(0);
     private Set organizacionOrdentrabajos = new HashSet(0);
     private Set productoProductos = new HashSet(0);
     private Set productoActivos = new HashSet(0);
     private Set organizacionDetordenservicios = new HashSet(0);
     private Set productoInventarios = new HashSet(0);

    public GeneralEstado() {
    }

	
    public GeneralEstado(String nombre, String descripcion, String abreviacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioModificacion = usuarioModificacion;
        this.estadoRegistro = estadoRegistro;
    }
    public GeneralEstado(String nombre, String descripcion, String abreviacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro, Set organizacionDetordentrabajos, Set organizacionOrdenservicios, Set productoResponsableactivos, Set productoProductoatributos, Set productoRelacionproductos, Set organizacionOrdentrabajos, Set productoProductos, Set productoActivos, Set organizacionDetordenservicios, Set productoInventarios) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
       this.organizacionDetordentrabajos = organizacionDetordentrabajos;
       this.organizacionOrdenservicios = organizacionOrdenservicios;
       this.productoResponsableactivos = productoResponsableactivos;
       this.productoProductoatributos = productoProductoatributos;
       this.productoRelacionproductos = productoRelacionproductos;
       this.organizacionOrdentrabajos = organizacionOrdentrabajos;
       this.productoProductos = productoProductos;
       this.productoActivos = productoActivos;
       this.organizacionDetordenservicios = organizacionDetordenservicios;
       this.productoInventarios = productoInventarios;
    }
   
    public Integer getEstadoId() {
        return this.estadoId;
    }
    
    public void setEstadoId(Integer estadoId) {
        this.estadoId = estadoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getOrganizacionDetordentrabajos() {
        return this.organizacionDetordentrabajos;
    }
    
    public void setOrganizacionDetordentrabajos(Set organizacionDetordentrabajos) {
        this.organizacionDetordentrabajos = organizacionDetordentrabajos;
    }
    public Set getOrganizacionOrdenservicios() {
        return this.organizacionOrdenservicios;
    }
    
    public void setOrganizacionOrdenservicios(Set organizacionOrdenservicios) {
        this.organizacionOrdenservicios = organizacionOrdenservicios;
    }
    public Set getProductoResponsableactivos() {
        return this.productoResponsableactivos;
    }
    
    public void setProductoResponsableactivos(Set productoResponsableactivos) {
        this.productoResponsableactivos = productoResponsableactivos;
    }
    public Set getProductoProductoatributos() {
        return this.productoProductoatributos;
    }
    
    public void setProductoProductoatributos(Set productoProductoatributos) {
        this.productoProductoatributos = productoProductoatributos;
    }
    public Set getProductoRelacionproductos() {
        return this.productoRelacionproductos;
    }
    
    public void setProductoRelacionproductos(Set productoRelacionproductos) {
        this.productoRelacionproductos = productoRelacionproductos;
    }
    public Set getOrganizacionOrdentrabajos() {
        return this.organizacionOrdentrabajos;
    }
    
    public void setOrganizacionOrdentrabajos(Set organizacionOrdentrabajos) {
        this.organizacionOrdentrabajos = organizacionOrdentrabajos;
    }
    public Set getProductoProductos() {
        return this.productoProductos;
    }
    
    public void setProductoProductos(Set productoProductos) {
        this.productoProductos = productoProductos;
    }
    public Set getProductoActivos() {
        return this.productoActivos;
    }
    
    public void setProductoActivos(Set productoActivos) {
        this.productoActivos = productoActivos;
    }
    public Set getOrganizacionDetordenservicios() {
        return this.organizacionDetordenservicios;
    }
    
    public void setOrganizacionDetordenservicios(Set organizacionDetordenservicios) {
        this.organizacionDetordenservicios = organizacionDetordenservicios;
    }
    public Set getProductoInventarios() {
        return this.productoInventarios;
    }
    
    public void setProductoInventarios(Set productoInventarios) {
        this.productoInventarios = productoInventarios;
    }




}


