package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GeneralCategoriaactividad generated by hbm2java
 */
public class GeneralCategoriaactividad  implements java.io.Serializable {


     private Integer categoriaActividadId;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean categoriaActividadRegistro;
     private Set generalMotivoactividads = new HashSet(0);

    public GeneralCategoriaactividad() {
    }

	
    public GeneralCategoriaactividad(String nombre, String descripcion, String abreviacion, Date fechaModificacion, String usuarioModificacion, boolean categoriaActividadRegistro) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioModificacion = usuarioModificacion;
        this.categoriaActividadRegistro = categoriaActividadRegistro;
    }
    public GeneralCategoriaactividad(String nombre, String descripcion, String abreviacion, Date fechaModificacion, String usuarioModificacion, boolean categoriaActividadRegistro, Set generalMotivoactividads) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.categoriaActividadRegistro = categoriaActividadRegistro;
       this.generalMotivoactividads = generalMotivoactividads;
    }
   
    public Integer getCategoriaActividadId() {
        return this.categoriaActividadId;
    }
    
    public void setCategoriaActividadId(Integer categoriaActividadId) {
        this.categoriaActividadId = categoriaActividadId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isCategoriaActividadRegistro() {
        return this.categoriaActividadRegistro;
    }
    
    public void setCategoriaActividadRegistro(boolean categoriaActividadRegistro) {
        this.categoriaActividadRegistro = categoriaActividadRegistro;
    }
    public Set getGeneralMotivoactividads() {
        return this.generalMotivoactividads;
    }
    
    public void setGeneralMotivoactividads(Set generalMotivoactividads) {
        this.generalMotivoactividads = generalMotivoactividads;
    }




}


