package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LogisticaLocacion generated by hbm2java
 */
public class LogisticaLocacion  implements java.io.Serializable {


     private Integer locacionId;
     private LogisticaDistrito logisticaDistrito;
     private LogisticaProvincia logisticaProvincia;
     private OrganizacionOrganizacion organizacionOrganizacion;
     private PersonaDireccionentidad personaDireccionentidad;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private long latitud;
     private long longitud;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;
     private Set productoActivos = new HashSet(0);
     private Set logisticaRutasForLocacionDestinoId = new HashSet(0);
     private Set productoInventarios = new HashSet(0);
     private Set logisticaRutasForLocacionOrigenId = new HashSet(0);

    public LogisticaLocacion() {
    }

	
    public LogisticaLocacion(LogisticaDistrito logisticaDistrito, LogisticaProvincia logisticaProvincia, OrganizacionOrganizacion organizacionOrganizacion, PersonaDireccionentidad personaDireccionentidad, String nombre, String descripcion, String abreviacion, long latitud, long longitud, Date fechaCreacion, boolean estadoRegistro) {
        this.logisticaDistrito = logisticaDistrito;
        this.logisticaProvincia = logisticaProvincia;
        this.organizacionOrganizacion = organizacionOrganizacion;
        this.personaDireccionentidad = personaDireccionentidad;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.latitud = latitud;
        this.longitud = longitud;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public LogisticaLocacion(LogisticaDistrito logisticaDistrito, LogisticaProvincia logisticaProvincia, OrganizacionOrganizacion organizacionOrganizacion, PersonaDireccionentidad personaDireccionentidad, String nombre, String descripcion, String abreviacion, long latitud, long longitud, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, Set productoActivos, Set logisticaRutasForLocacionDestinoId, Set productoInventarios, Set logisticaRutasForLocacionOrigenId) {
       this.logisticaDistrito = logisticaDistrito;
       this.logisticaProvincia = logisticaProvincia;
       this.organizacionOrganizacion = organizacionOrganizacion;
       this.personaDireccionentidad = personaDireccionentidad;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.latitud = latitud;
       this.longitud = longitud;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.productoActivos = productoActivos;
       this.logisticaRutasForLocacionDestinoId = logisticaRutasForLocacionDestinoId;
       this.productoInventarios = productoInventarios;
       this.logisticaRutasForLocacionOrigenId = logisticaRutasForLocacionOrigenId;
    }
   
    public Integer getLocacionId() {
        return this.locacionId;
    }
    
    public void setLocacionId(Integer locacionId) {
        this.locacionId = locacionId;
    }
    public LogisticaDistrito getLogisticaDistrito() {
        return this.logisticaDistrito;
    }
    
    public void setLogisticaDistrito(LogisticaDistrito logisticaDistrito) {
        this.logisticaDistrito = logisticaDistrito;
    }
    public LogisticaProvincia getLogisticaProvincia() {
        return this.logisticaProvincia;
    }
    
    public void setLogisticaProvincia(LogisticaProvincia logisticaProvincia) {
        this.logisticaProvincia = logisticaProvincia;
    }
    public OrganizacionOrganizacion getOrganizacionOrganizacion() {
        return this.organizacionOrganizacion;
    }
    
    public void setOrganizacionOrganizacion(OrganizacionOrganizacion organizacionOrganizacion) {
        this.organizacionOrganizacion = organizacionOrganizacion;
    }
    public PersonaDireccionentidad getPersonaDireccionentidad() {
        return this.personaDireccionentidad;
    }
    
    public void setPersonaDireccionentidad(PersonaDireccionentidad personaDireccionentidad) {
        this.personaDireccionentidad = personaDireccionentidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public long getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(long latitud) {
        this.latitud = latitud;
    }
    public long getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(long longitud) {
        this.longitud = longitud;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getProductoActivos() {
        return this.productoActivos;
    }
    
    public void setProductoActivos(Set productoActivos) {
        this.productoActivos = productoActivos;
    }
    public Set getLogisticaRutasForLocacionDestinoId() {
        return this.logisticaRutasForLocacionDestinoId;
    }
    
    public void setLogisticaRutasForLocacionDestinoId(Set logisticaRutasForLocacionDestinoId) {
        this.logisticaRutasForLocacionDestinoId = logisticaRutasForLocacionDestinoId;
    }
    public Set getProductoInventarios() {
        return this.productoInventarios;
    }
    
    public void setProductoInventarios(Set productoInventarios) {
        this.productoInventarios = productoInventarios;
    }
    public Set getLogisticaRutasForLocacionOrigenId() {
        return this.logisticaRutasForLocacionOrigenId;
    }
    
    public void setLogisticaRutasForLocacionOrigenId(Set logisticaRutasForLocacionOrigenId) {
        this.logisticaRutasForLocacionOrigenId = logisticaRutasForLocacionOrigenId;
    }




}


