package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LogisticaDepartamento generated by hbm2java
 */
public class LogisticaDepartamento  implements java.io.Serializable {


     private Integer departamentoId;
     private LogisticaPais logisticaPais;
     private String nombre;
     private String codigo;
     private int zonaHoraria;
     private String codigoPostal;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;
     private Set logisticaProvincias = new HashSet(0);

    public LogisticaDepartamento() {
    }

	
    public LogisticaDepartamento(LogisticaPais logisticaPais, String nombre, String codigo, int zonaHoraria, String codigoPostal, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro) {
        this.logisticaPais = logisticaPais;
        this.nombre = nombre;
        this.codigo = codigo;
        this.zonaHoraria = zonaHoraria;
        this.codigoPostal = codigoPostal;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.estadoRegistro = estadoRegistro;
    }
    public LogisticaDepartamento(LogisticaPais logisticaPais, String nombre, String codigo, int zonaHoraria, String codigoPostal, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, Set logisticaProvincias) {
       this.logisticaPais = logisticaPais;
       this.nombre = nombre;
       this.codigo = codigo;
       this.zonaHoraria = zonaHoraria;
       this.codigoPostal = codigoPostal;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.logisticaProvincias = logisticaProvincias;
    }
   
    public Integer getDepartamentoId() {
        return this.departamentoId;
    }
    
    public void setDepartamentoId(Integer departamentoId) {
        this.departamentoId = departamentoId;
    }
    public LogisticaPais getLogisticaPais() {
        return this.logisticaPais;
    }
    
    public void setLogisticaPais(LogisticaPais logisticaPais) {
        this.logisticaPais = logisticaPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public int getZonaHoraria() {
        return this.zonaHoraria;
    }
    
    public void setZonaHoraria(int zonaHoraria) {
        this.zonaHoraria = zonaHoraria;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getLogisticaProvincias() {
        return this.logisticaProvincias;
    }
    
    public void setLogisticaProvincias(Set logisticaProvincias) {
        this.logisticaProvincias = logisticaProvincias;
    }




}


