package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LogisticaDistrito generated by hbm2java
 */
public class LogisticaDistrito  implements java.io.Serializable {


     private Integer distritoId;
     private LogisticaProvincia logisticaProvincia;
     private String nombre;
     private String codigo;
     private String codigoPostal;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;
     private Set personaDireccionentidads = new HashSet(0);
     private Set logisticaLocacions = new HashSet(0);

    public LogisticaDistrito() {
    }

	
    public LogisticaDistrito(LogisticaProvincia logisticaProvincia, String nombre, String codigo, String codigoPostal, Date fechaCreacion, boolean estadoRegistro) {
        this.logisticaProvincia = logisticaProvincia;
        this.nombre = nombre;
        this.codigo = codigo;
        this.codigoPostal = codigoPostal;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public LogisticaDistrito(LogisticaProvincia logisticaProvincia, String nombre, String codigo, String codigoPostal, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, Set personaDireccionentidads, Set logisticaLocacions) {
       this.logisticaProvincia = logisticaProvincia;
       this.nombre = nombre;
       this.codigo = codigo;
       this.codigoPostal = codigoPostal;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.personaDireccionentidads = personaDireccionentidads;
       this.logisticaLocacions = logisticaLocacions;
    }
   
    public Integer getDistritoId() {
        return this.distritoId;
    }
    
    public void setDistritoId(Integer distritoId) {
        this.distritoId = distritoId;
    }
    public LogisticaProvincia getLogisticaProvincia() {
        return this.logisticaProvincia;
    }
    
    public void setLogisticaProvincia(LogisticaProvincia logisticaProvincia) {
        this.logisticaProvincia = logisticaProvincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getPersonaDireccionentidads() {
        return this.personaDireccionentidads;
    }
    
    public void setPersonaDireccionentidads(Set personaDireccionentidads) {
        this.personaDireccionentidads = personaDireccionentidads;
    }
    public Set getLogisticaLocacions() {
        return this.logisticaLocacions;
    }
    
    public void setLogisticaLocacions(Set logisticaLocacions) {
        this.logisticaLocacions = logisticaLocacions;
    }




}


