package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LogisticaPais generated by hbm2java
 */
public class LogisticaPais  implements java.io.Serializable {


     private Integer paisId;
     private String nombre;
     private String codigoIso;
     private String moneda;
     private int zonaHoraria;
     private String codigoPostal;
     private boolean inmutable;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;
     private Set logisticaDepartamentos = new HashSet(0);

    public LogisticaPais() {
    }

	
    public LogisticaPais(String nombre, String codigoIso, String moneda, int zonaHoraria, String codigoPostal, boolean inmutable, Date fechaCreacion, boolean estadoRegistro) {
        this.nombre = nombre;
        this.codigoIso = codigoIso;
        this.moneda = moneda;
        this.zonaHoraria = zonaHoraria;
        this.codigoPostal = codigoPostal;
        this.inmutable = inmutable;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public LogisticaPais(String nombre, String codigoIso, String moneda, int zonaHoraria, String codigoPostal, boolean inmutable, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, Set logisticaDepartamentos) {
       this.nombre = nombre;
       this.codigoIso = codigoIso;
       this.moneda = moneda;
       this.zonaHoraria = zonaHoraria;
       this.codigoPostal = codigoPostal;
       this.inmutable = inmutable;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.logisticaDepartamentos = logisticaDepartamentos;
    }
   
    public Integer getPaisId() {
        return this.paisId;
    }
    
    public void setPaisId(Integer paisId) {
        this.paisId = paisId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigoIso() {
        return this.codigoIso;
    }
    
    public void setCodigoIso(String codigoIso) {
        this.codigoIso = codigoIso;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public int getZonaHoraria() {
        return this.zonaHoraria;
    }
    
    public void setZonaHoraria(int zonaHoraria) {
        this.zonaHoraria = zonaHoraria;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public boolean isInmutable() {
        return this.inmutable;
    }
    
    public void setInmutable(boolean inmutable) {
        this.inmutable = inmutable;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getLogisticaDepartamentos() {
        return this.logisticaDepartamentos;
    }
    
    public void setLogisticaDepartamentos(Set logisticaDepartamentos) {
        this.logisticaDepartamentos = logisticaDepartamentos;
    }




}


