package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LogisticaProvincia generated by hbm2java
 */
public class LogisticaProvincia  implements java.io.Serializable {


     private Integer provinciaId;
     private LogisticaDepartamento logisticaDepartamento;
     private String nombre;
     private String codigo;
     private String codigoPostal;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;
     private Set logisticaLocacions = new HashSet(0);
     private Set logisticaDistritos = new HashSet(0);

    public LogisticaProvincia() {
    }

	
    public LogisticaProvincia(LogisticaDepartamento logisticaDepartamento, String nombre, String codigo, String codigoPostal, Date fechaCreacion, boolean estadoRegistro) {
        this.logisticaDepartamento = logisticaDepartamento;
        this.nombre = nombre;
        this.codigo = codigo;
        this.codigoPostal = codigoPostal;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public LogisticaProvincia(LogisticaDepartamento logisticaDepartamento, String nombre, String codigo, String codigoPostal, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, Set logisticaLocacions, Set logisticaDistritos) {
       this.logisticaDepartamento = logisticaDepartamento;
       this.nombre = nombre;
       this.codigo = codigo;
       this.codigoPostal = codigoPostal;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.logisticaLocacions = logisticaLocacions;
       this.logisticaDistritos = logisticaDistritos;
    }
   
    public Integer getProvinciaId() {
        return this.provinciaId;
    }
    
    public void setProvinciaId(Integer provinciaId) {
        this.provinciaId = provinciaId;
    }
    public LogisticaDepartamento getLogisticaDepartamento() {
        return this.logisticaDepartamento;
    }
    
    public void setLogisticaDepartamento(LogisticaDepartamento logisticaDepartamento) {
        this.logisticaDepartamento = logisticaDepartamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getLogisticaLocacions() {
        return this.logisticaLocacions;
    }
    
    public void setLogisticaLocacions(Set logisticaLocacions) {
        this.logisticaLocacions = logisticaLocacions;
    }
    public Set getLogisticaDistritos() {
        return this.logisticaDistritos;
    }
    
    public void setLogisticaDistritos(Set logisticaDistritos) {
        this.logisticaDistritos = logisticaDistritos;
    }




}


