package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LogisticaUsodireccion generated by hbm2java
 */
public class LogisticaUsodireccion  implements java.io.Serializable {


     private Integer usoDireccionId;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;
     private Set personaDireccionentidads = new HashSet(0);

    public LogisticaUsodireccion() {
    }

	
    public LogisticaUsodireccion(String nombre, String descripcion, String abreviacion, Date fechaCreacion, boolean estadoRegistro) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public LogisticaUsodireccion(String nombre, String descripcion, String abreviacion, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, Set personaDireccionentidads) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.personaDireccionentidads = personaDireccionentidads;
    }
   
    public Integer getUsoDireccionId() {
        return this.usoDireccionId;
    }
    
    public void setUsoDireccionId(Integer usoDireccionId) {
        this.usoDireccionId = usoDireccionId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getPersonaDireccionentidads() {
        return this.personaDireccionentidads;
    }
    
    public void setPersonaDireccionentidads(Set personaDireccionentidads) {
        this.personaDireccionentidads = personaDireccionentidads;
    }




}


