package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrganizacionOrdenservicio generated by hbm2java
 */
public class OrganizacionOrdenservicio  implements java.io.Serializable {


     private Integer ordenServicioId;
     private GeneralEstado generalEstado;
     private OrganizacionCliente organizacionCliente;
     private OrganizacionOrganizacion organizacionOrganizacion;
     private OrganizacionTrabajador organizacionTrabajador;
     private PersonaPersona personaPersona;
     private String codigo;
     private String nombre;
     private String descripcion;
     private int contratoServicioId;
     private Date fechaInicio;
     private Date fechaFin;
     private int prioridadId;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;
     private Set organizacionDetordenservicios = new HashSet(0);

    public OrganizacionOrdenservicio() {
    }

	
    public OrganizacionOrdenservicio(GeneralEstado generalEstado, OrganizacionCliente organizacionCliente, OrganizacionOrganizacion organizacionOrganizacion, OrganizacionTrabajador organizacionTrabajador, PersonaPersona personaPersona, String codigo, String nombre, String descripcion, int contratoServicioId, Date fechaInicio, Date fechaFin, int prioridadId, Date fechaCreacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
        this.generalEstado = generalEstado;
        this.organizacionCliente = organizacionCliente;
        this.organizacionOrganizacion = organizacionOrganizacion;
        this.organizacionTrabajador = organizacionTrabajador;
        this.personaPersona = personaPersona;
        this.codigo = codigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.contratoServicioId = contratoServicioId;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.prioridadId = prioridadId;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioModificacion = usuarioModificacion;
        this.estadoRegistro = estadoRegistro;
    }
    public OrganizacionOrdenservicio(GeneralEstado generalEstado, OrganizacionCliente organizacionCliente, OrganizacionOrganizacion organizacionOrganizacion, OrganizacionTrabajador organizacionTrabajador, PersonaPersona personaPersona, String codigo, String nombre, String descripcion, int contratoServicioId, Date fechaInicio, Date fechaFin, int prioridadId, Date fechaCreacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro, Set organizacionDetordenservicios) {
       this.generalEstado = generalEstado;
       this.organizacionCliente = organizacionCliente;
       this.organizacionOrganizacion = organizacionOrganizacion;
       this.organizacionTrabajador = organizacionTrabajador;
       this.personaPersona = personaPersona;
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.contratoServicioId = contratoServicioId;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.prioridadId = prioridadId;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
       this.organizacionDetordenservicios = organizacionDetordenservicios;
    }
   
    public Integer getOrdenServicioId() {
        return this.ordenServicioId;
    }
    
    public void setOrdenServicioId(Integer ordenServicioId) {
        this.ordenServicioId = ordenServicioId;
    }
    public GeneralEstado getGeneralEstado() {
        return this.generalEstado;
    }
    
    public void setGeneralEstado(GeneralEstado generalEstado) {
        this.generalEstado = generalEstado;
    }
    public OrganizacionCliente getOrganizacionCliente() {
        return this.organizacionCliente;
    }
    
    public void setOrganizacionCliente(OrganizacionCliente organizacionCliente) {
        this.organizacionCliente = organizacionCliente;
    }
    public OrganizacionOrganizacion getOrganizacionOrganizacion() {
        return this.organizacionOrganizacion;
    }
    
    public void setOrganizacionOrganizacion(OrganizacionOrganizacion organizacionOrganizacion) {
        this.organizacionOrganizacion = organizacionOrganizacion;
    }
    public OrganizacionTrabajador getOrganizacionTrabajador() {
        return this.organizacionTrabajador;
    }
    
    public void setOrganizacionTrabajador(OrganizacionTrabajador organizacionTrabajador) {
        this.organizacionTrabajador = organizacionTrabajador;
    }
    public PersonaPersona getPersonaPersona() {
        return this.personaPersona;
    }
    
    public void setPersonaPersona(PersonaPersona personaPersona) {
        this.personaPersona = personaPersona;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getContratoServicioId() {
        return this.contratoServicioId;
    }
    
    public void setContratoServicioId(int contratoServicioId) {
        this.contratoServicioId = contratoServicioId;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public int getPrioridadId() {
        return this.prioridadId;
    }
    
    public void setPrioridadId(int prioridadId) {
        this.prioridadId = prioridadId;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getOrganizacionDetordenservicios() {
        return this.organizacionDetordenservicios;
    }
    
    public void setOrganizacionDetordenservicios(Set organizacionDetordenservicios) {
        this.organizacionDetordenservicios = organizacionDetordenservicios;
    }




}


