package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrganizacionOrganizacion generated by hbm2java
 */
public class OrganizacionOrganizacion  implements java.io.Serializable {


     private int entidadNegocioId;
     private OrganizacionGiro organizacionGiro;
     private OrganizacionRazonsocial organizacionRazonsocial;
     private OrganizacionTipoorganizacion organizacionTipoorganizacion;
     private PersonaEntidadnegocio personaEntidadnegocio;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;
     private Set organizacionOrdentrabajos = new HashSet(0);
     private Set productoProductos = new HashSet(0);
     private Set logisticaLocacions = new HashSet(0);
     private Set organizacionOrdenservicios = new HashSet(0);
     private Set organizacionServicios = new HashSet(0);
     private Set logisticaRutas = new HashSet(0);
     private Set organizacionClientes = new HashSet(0);
     private Set organizacionTrabajadors = new HashSet(0);

    public OrganizacionOrganizacion() {
    }

	
    public OrganizacionOrganizacion(OrganizacionGiro organizacionGiro, OrganizacionRazonsocial organizacionRazonsocial, OrganizacionTipoorganizacion organizacionTipoorganizacion, PersonaEntidadnegocio personaEntidadnegocio, String nombre, String descripcion, String abreviacion, Date fechaCreacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
        this.organizacionGiro = organizacionGiro;
        this.organizacionRazonsocial = organizacionRazonsocial;
        this.organizacionTipoorganizacion = organizacionTipoorganizacion;
        this.personaEntidadnegocio = personaEntidadnegocio;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioModificacion = usuarioModificacion;
        this.estadoRegistro = estadoRegistro;
    }
    public OrganizacionOrganizacion(OrganizacionGiro organizacionGiro, OrganizacionRazonsocial organizacionRazonsocial, OrganizacionTipoorganizacion organizacionTipoorganizacion, PersonaEntidadnegocio personaEntidadnegocio, String nombre, String descripcion, String abreviacion, Date fechaCreacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro, Set organizacionOrdentrabajos, Set productoProductos, Set logisticaLocacions, Set organizacionOrdenservicios, Set organizacionServicios, Set logisticaRutas, Set organizacionClientes, Set organizacionTrabajadors) {
       this.organizacionGiro = organizacionGiro;
       this.organizacionRazonsocial = organizacionRazonsocial;
       this.organizacionTipoorganizacion = organizacionTipoorganizacion;
       this.personaEntidadnegocio = personaEntidadnegocio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
       this.organizacionOrdentrabajos = organizacionOrdentrabajos;
       this.productoProductos = productoProductos;
       this.logisticaLocacions = logisticaLocacions;
       this.organizacionOrdenservicios = organizacionOrdenservicios;
       this.organizacionServicios = organizacionServicios;
       this.logisticaRutas = logisticaRutas;
       this.organizacionClientes = organizacionClientes;
       this.organizacionTrabajadors = organizacionTrabajadors;
    }
   
    public int getEntidadNegocioId() {
        return this.entidadNegocioId;
    }
    
    public void setEntidadNegocioId(int entidadNegocioId) {
        this.entidadNegocioId = entidadNegocioId;
    }
    public OrganizacionGiro getOrganizacionGiro() {
        return this.organizacionGiro;
    }
    
    public void setOrganizacionGiro(OrganizacionGiro organizacionGiro) {
        this.organizacionGiro = organizacionGiro;
    }
    public OrganizacionRazonsocial getOrganizacionRazonsocial() {
        return this.organizacionRazonsocial;
    }
    
    public void setOrganizacionRazonsocial(OrganizacionRazonsocial organizacionRazonsocial) {
        this.organizacionRazonsocial = organizacionRazonsocial;
    }
    public OrganizacionTipoorganizacion getOrganizacionTipoorganizacion() {
        return this.organizacionTipoorganizacion;
    }
    
    public void setOrganizacionTipoorganizacion(OrganizacionTipoorganizacion organizacionTipoorganizacion) {
        this.organizacionTipoorganizacion = organizacionTipoorganizacion;
    }
    public PersonaEntidadnegocio getPersonaEntidadnegocio() {
        return this.personaEntidadnegocio;
    }
    
    public void setPersonaEntidadnegocio(PersonaEntidadnegocio personaEntidadnegocio) {
        this.personaEntidadnegocio = personaEntidadnegocio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getOrganizacionOrdentrabajos() {
        return this.organizacionOrdentrabajos;
    }
    
    public void setOrganizacionOrdentrabajos(Set organizacionOrdentrabajos) {
        this.organizacionOrdentrabajos = organizacionOrdentrabajos;
    }
    public Set getProductoProductos() {
        return this.productoProductos;
    }
    
    public void setProductoProductos(Set productoProductos) {
        this.productoProductos = productoProductos;
    }
    public Set getLogisticaLocacions() {
        return this.logisticaLocacions;
    }
    
    public void setLogisticaLocacions(Set logisticaLocacions) {
        this.logisticaLocacions = logisticaLocacions;
    }
    public Set getOrganizacionOrdenservicios() {
        return this.organizacionOrdenservicios;
    }
    
    public void setOrganizacionOrdenservicios(Set organizacionOrdenservicios) {
        this.organizacionOrdenservicios = organizacionOrdenservicios;
    }
    public Set getOrganizacionServicios() {
        return this.organizacionServicios;
    }
    
    public void setOrganizacionServicios(Set organizacionServicios) {
        this.organizacionServicios = organizacionServicios;
    }
    public Set getLogisticaRutas() {
        return this.logisticaRutas;
    }
    
    public void setLogisticaRutas(Set logisticaRutas) {
        this.logisticaRutas = logisticaRutas;
    }
    public Set getOrganizacionClientes() {
        return this.organizacionClientes;
    }
    
    public void setOrganizacionClientes(Set organizacionClientes) {
        this.organizacionClientes = organizacionClientes;
    }
    public Set getOrganizacionTrabajadors() {
        return this.organizacionTrabajadors;
    }
    
    public void setOrganizacionTrabajadors(Set organizacionTrabajadors) {
        this.organizacionTrabajadors = organizacionTrabajadors;
    }




}


