package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrganizacionDetordenservicio generated by hbm2java
 */
public class OrganizacionDetordenservicio  implements java.io.Serializable {


     private Integer detOrdenServicioId;
     private GeneralEstado generalEstado;
     private GeneralMotivoactividad generalMotivoactividad;
     private OrganizacionOrdenservicio organizacionOrdenservicio;
     private OrganizacionServicio organizacionServicio;
     private OrganizacionTrabajador organizacionTrabajador;
     private ProductoInventario productoInventario;
     private String descripcion;
     private Date fechaEstimada;
     private Date fechaInicio;
     private Date fechaFin;
     private Date validoDesde;
     private Date validoHasta;
     private String observacion;
     private int detContratoServicioId;
     private String ruta;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;

    public OrganizacionDetordenservicio() {
    }

    public OrganizacionDetordenservicio(GeneralEstado generalEstado, GeneralMotivoactividad generalMotivoactividad, OrganizacionOrdenservicio organizacionOrdenservicio, OrganizacionServicio organizacionServicio, OrganizacionTrabajador organizacionTrabajador, ProductoInventario productoInventario, String descripcion, Date fechaEstimada, Date fechaInicio, Date fechaFin, Date validoDesde, Date validoHasta, String observacion, int detContratoServicioId, String ruta, Date fechaCreacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
       this.generalEstado = generalEstado;
       this.generalMotivoactividad = generalMotivoactividad;
       this.organizacionOrdenservicio = organizacionOrdenservicio;
       this.organizacionServicio = organizacionServicio;
       this.organizacionTrabajador = organizacionTrabajador;
       this.productoInventario = productoInventario;
       this.descripcion = descripcion;
       this.fechaEstimada = fechaEstimada;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.validoDesde = validoDesde;
       this.validoHasta = validoHasta;
       this.observacion = observacion;
       this.detContratoServicioId = detContratoServicioId;
       this.ruta = ruta;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Integer getDetOrdenServicioId() {
        return this.detOrdenServicioId;
    }
    
    public void setDetOrdenServicioId(Integer detOrdenServicioId) {
        this.detOrdenServicioId = detOrdenServicioId;
    }
    public GeneralEstado getGeneralEstado() {
        return this.generalEstado;
    }
    
    public void setGeneralEstado(GeneralEstado generalEstado) {
        this.generalEstado = generalEstado;
    }
    public GeneralMotivoactividad getGeneralMotivoactividad() {
        return this.generalMotivoactividad;
    }
    
    public void setGeneralMotivoactividad(GeneralMotivoactividad generalMotivoactividad) {
        this.generalMotivoactividad = generalMotivoactividad;
    }
    public OrganizacionOrdenservicio getOrganizacionOrdenservicio() {
        return this.organizacionOrdenservicio;
    }
    
    public void setOrganizacionOrdenservicio(OrganizacionOrdenservicio organizacionOrdenservicio) {
        this.organizacionOrdenservicio = organizacionOrdenservicio;
    }
    public OrganizacionServicio getOrganizacionServicio() {
        return this.organizacionServicio;
    }
    
    public void setOrganizacionServicio(OrganizacionServicio organizacionServicio) {
        this.organizacionServicio = organizacionServicio;
    }
    public OrganizacionTrabajador getOrganizacionTrabajador() {
        return this.organizacionTrabajador;
    }
    
    public void setOrganizacionTrabajador(OrganizacionTrabajador organizacionTrabajador) {
        this.organizacionTrabajador = organizacionTrabajador;
    }
    public ProductoInventario getProductoInventario() {
        return this.productoInventario;
    }
    
    public void setProductoInventario(ProductoInventario productoInventario) {
        this.productoInventario = productoInventario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaEstimada() {
        return this.fechaEstimada;
    }
    
    public void setFechaEstimada(Date fechaEstimada) {
        this.fechaEstimada = fechaEstimada;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Date getValidoDesde() {
        return this.validoDesde;
    }
    
    public void setValidoDesde(Date validoDesde) {
        this.validoDesde = validoDesde;
    }
    public Date getValidoHasta() {
        return this.validoHasta;
    }
    
    public void setValidoHasta(Date validoHasta) {
        this.validoHasta = validoHasta;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public int getDetContratoServicioId() {
        return this.detContratoServicioId;
    }
    
    public void setDetContratoServicioId(int detContratoServicioId) {
        this.detContratoServicioId = detContratoServicioId;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


