package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrganizacionCliente generated by hbm2java
 */
public class OrganizacionCliente  implements java.io.Serializable {


     private Integer clienteId;
     private OrganizacionOrganizacion organizacionOrganizacion;
     private PersonaEntidadnegocio personaEntidadnegocioByEntidadNegocioId;
     private PersonaEntidadnegocio personaEntidadnegocioByContactoId;
     private String nombre;
     private String numeroCuenta;
     private String cuentaBancaria;
     private long creditoLimite;
     private String calificacionCrediticia;
     private String codigo;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;
     private Set organizacionOrdenservicios = new HashSet(0);

    public OrganizacionCliente() {
    }

	
    public OrganizacionCliente(OrganizacionOrganizacion organizacionOrganizacion, PersonaEntidadnegocio personaEntidadnegocioByEntidadNegocioId, PersonaEntidadnegocio personaEntidadnegocioByContactoId, String nombre, String numeroCuenta, String cuentaBancaria, long creditoLimite, String calificacionCrediticia, String codigo, Date fechaCreacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
        this.organizacionOrganizacion = organizacionOrganizacion;
        this.personaEntidadnegocioByEntidadNegocioId = personaEntidadnegocioByEntidadNegocioId;
        this.personaEntidadnegocioByContactoId = personaEntidadnegocioByContactoId;
        this.nombre = nombre;
        this.numeroCuenta = numeroCuenta;
        this.cuentaBancaria = cuentaBancaria;
        this.creditoLimite = creditoLimite;
        this.calificacionCrediticia = calificacionCrediticia;
        this.codigo = codigo;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioModificacion = usuarioModificacion;
        this.estadoRegistro = estadoRegistro;
    }
    public OrganizacionCliente(OrganizacionOrganizacion organizacionOrganizacion, PersonaEntidadnegocio personaEntidadnegocioByEntidadNegocioId, PersonaEntidadnegocio personaEntidadnegocioByContactoId, String nombre, String numeroCuenta, String cuentaBancaria, long creditoLimite, String calificacionCrediticia, String codigo, Date fechaCreacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro, Set organizacionOrdenservicios) {
       this.organizacionOrganizacion = organizacionOrganizacion;
       this.personaEntidadnegocioByEntidadNegocioId = personaEntidadnegocioByEntidadNegocioId;
       this.personaEntidadnegocioByContactoId = personaEntidadnegocioByContactoId;
       this.nombre = nombre;
       this.numeroCuenta = numeroCuenta;
       this.cuentaBancaria = cuentaBancaria;
       this.creditoLimite = creditoLimite;
       this.calificacionCrediticia = calificacionCrediticia;
       this.codigo = codigo;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
       this.organizacionOrdenservicios = organizacionOrdenservicios;
    }
   
    public Integer getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Integer clienteId) {
        this.clienteId = clienteId;
    }
    public OrganizacionOrganizacion getOrganizacionOrganizacion() {
        return this.organizacionOrganizacion;
    }
    
    public void setOrganizacionOrganizacion(OrganizacionOrganizacion organizacionOrganizacion) {
        this.organizacionOrganizacion = organizacionOrganizacion;
    }
    public PersonaEntidadnegocio getPersonaEntidadnegocioByEntidadNegocioId() {
        return this.personaEntidadnegocioByEntidadNegocioId;
    }
    
    public void setPersonaEntidadnegocioByEntidadNegocioId(PersonaEntidadnegocio personaEntidadnegocioByEntidadNegocioId) {
        this.personaEntidadnegocioByEntidadNegocioId = personaEntidadnegocioByEntidadNegocioId;
    }
    public PersonaEntidadnegocio getPersonaEntidadnegocioByContactoId() {
        return this.personaEntidadnegocioByContactoId;
    }
    
    public void setPersonaEntidadnegocioByContactoId(PersonaEntidadnegocio personaEntidadnegocioByContactoId) {
        this.personaEntidadnegocioByContactoId = personaEntidadnegocioByContactoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }
    public String getCuentaBancaria() {
        return this.cuentaBancaria;
    }
    
    public void setCuentaBancaria(String cuentaBancaria) {
        this.cuentaBancaria = cuentaBancaria;
    }
    public long getCreditoLimite() {
        return this.creditoLimite;
    }
    
    public void setCreditoLimite(long creditoLimite) {
        this.creditoLimite = creditoLimite;
    }
    public String getCalificacionCrediticia() {
        return this.calificacionCrediticia;
    }
    
    public void setCalificacionCrediticia(String calificacionCrediticia) {
        this.calificacionCrediticia = calificacionCrediticia;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getOrganizacionOrdenservicios() {
        return this.organizacionOrdenservicios;
    }
    
    public void setOrganizacionOrdenservicios(Set organizacionOrdenservicios) {
        this.organizacionOrdenservicios = organizacionOrdenservicios;
    }




}


