package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrganizacionProveedor generated by hbm2java
 */
public class OrganizacionProveedor  implements java.io.Serializable {


     private int entidadNegocioId;
     private PersonaEntidadnegocio personaEntidadnegocioByEntidadNegocioId;
     private PersonaEntidadnegocio personaEntidadnegocioByContactoId;
     private String nombre;
     private boolean bloqueado;
     private boolean unaVez;
     private long creditoMaximo;
     private String calificacionCrediticia;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;
     private Set productoProductos = new HashSet(0);

    public OrganizacionProveedor() {
    }

	
    public OrganizacionProveedor(PersonaEntidadnegocio personaEntidadnegocioByEntidadNegocioId, PersonaEntidadnegocio personaEntidadnegocioByContactoId, String nombre, boolean bloqueado, boolean unaVez, long creditoMaximo, String calificacionCrediticia, Date fechaCreacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
        this.personaEntidadnegocioByEntidadNegocioId = personaEntidadnegocioByEntidadNegocioId;
        this.personaEntidadnegocioByContactoId = personaEntidadnegocioByContactoId;
        this.nombre = nombre;
        this.bloqueado = bloqueado;
        this.unaVez = unaVez;
        this.creditoMaximo = creditoMaximo;
        this.calificacionCrediticia = calificacionCrediticia;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioModificacion = usuarioModificacion;
        this.estadoRegistro = estadoRegistro;
    }
    public OrganizacionProveedor(PersonaEntidadnegocio personaEntidadnegocioByEntidadNegocioId, PersonaEntidadnegocio personaEntidadnegocioByContactoId, String nombre, boolean bloqueado, boolean unaVez, long creditoMaximo, String calificacionCrediticia, Date fechaCreacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro, Set productoProductos) {
       this.personaEntidadnegocioByEntidadNegocioId = personaEntidadnegocioByEntidadNegocioId;
       this.personaEntidadnegocioByContactoId = personaEntidadnegocioByContactoId;
       this.nombre = nombre;
       this.bloqueado = bloqueado;
       this.unaVez = unaVez;
       this.creditoMaximo = creditoMaximo;
       this.calificacionCrediticia = calificacionCrediticia;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
       this.productoProductos = productoProductos;
    }
   
    public int getEntidadNegocioId() {
        return this.entidadNegocioId;
    }
    
    public void setEntidadNegocioId(int entidadNegocioId) {
        this.entidadNegocioId = entidadNegocioId;
    }
    public PersonaEntidadnegocio getPersonaEntidadnegocioByEntidadNegocioId() {
        return this.personaEntidadnegocioByEntidadNegocioId;
    }
    
    public void setPersonaEntidadnegocioByEntidadNegocioId(PersonaEntidadnegocio personaEntidadnegocioByEntidadNegocioId) {
        this.personaEntidadnegocioByEntidadNegocioId = personaEntidadnegocioByEntidadNegocioId;
    }
    public PersonaEntidadnegocio getPersonaEntidadnegocioByContactoId() {
        return this.personaEntidadnegocioByContactoId;
    }
    
    public void setPersonaEntidadnegocioByContactoId(PersonaEntidadnegocio personaEntidadnegocioByContactoId) {
        this.personaEntidadnegocioByContactoId = personaEntidadnegocioByContactoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public boolean isBloqueado() {
        return this.bloqueado;
    }
    
    public void setBloqueado(boolean bloqueado) {
        this.bloqueado = bloqueado;
    }
    public boolean isUnaVez() {
        return this.unaVez;
    }
    
    public void setUnaVez(boolean unaVez) {
        this.unaVez = unaVez;
    }
    public long getCreditoMaximo() {
        return this.creditoMaximo;
    }
    
    public void setCreditoMaximo(long creditoMaximo) {
        this.creditoMaximo = creditoMaximo;
    }
    public String getCalificacionCrediticia() {
        return this.calificacionCrediticia;
    }
    
    public void setCalificacionCrediticia(String calificacionCrediticia) {
        this.calificacionCrediticia = calificacionCrediticia;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getProductoProductos() {
        return this.productoProductos;
    }
    
    public void setProductoProductos(Set productoProductos) {
        this.productoProductos = productoProductos;
    }




}


