package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PersonaEntidadnegocio generated by hbm2java
 */
public class PersonaEntidadnegocio  implements java.io.Serializable {


     private Integer entidadNegocioId;
     private PersonaTipoentidad personaTipoentidad;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private Date fechaNacimiento;
     private Date fechaCese;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;
     private PersonaPersona personaPersona;
     private OrganizacionOrganizacion organizacionOrganizacion;
     private Set personaDocumentoentidads = new HashSet(0);
     private OrganizacionProveedor organizacionProveedorByEntidadNegocioId;
     private Set organizacionClientesForEntidadNegocioId = new HashSet(0);
     private Set personaDireccionentidads = new HashSet(0);
     private Set organizacionProveedorsForContactoId = new HashSet(0);
     private Set organizacionClientesForContactoId = new HashSet(0);

    public PersonaEntidadnegocio() {
    }

	
    public PersonaEntidadnegocio(PersonaTipoentidad personaTipoentidad, String nombre, String descripcion, String abreviacion, Date fechaNacimiento, Date fechaCese, Date fechaCreacion, boolean estadoRegistro) {
        this.personaTipoentidad = personaTipoentidad;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.fechaNacimiento = fechaNacimiento;
        this.fechaCese = fechaCese;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public PersonaEntidadnegocio(PersonaTipoentidad personaTipoentidad, String nombre, String descripcion, String abreviacion, Date fechaNacimiento, Date fechaCese, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, PersonaPersona personaPersona, OrganizacionOrganizacion organizacionOrganizacion, Set personaDocumentoentidads, OrganizacionProveedor organizacionProveedorByEntidadNegocioId, Set organizacionClientesForEntidadNegocioId, Set personaDireccionentidads, Set organizacionProveedorsForContactoId, Set organizacionClientesForContactoId) {
       this.personaTipoentidad = personaTipoentidad;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.fechaNacimiento = fechaNacimiento;
       this.fechaCese = fechaCese;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.personaPersona = personaPersona;
       this.organizacionOrganizacion = organizacionOrganizacion;
       this.personaDocumentoentidads = personaDocumentoentidads;
       this.organizacionProveedorByEntidadNegocioId = organizacionProveedorByEntidadNegocioId;
       this.organizacionClientesForEntidadNegocioId = organizacionClientesForEntidadNegocioId;
       this.personaDireccionentidads = personaDireccionentidads;
       this.organizacionProveedorsForContactoId = organizacionProveedorsForContactoId;
       this.organizacionClientesForContactoId = organizacionClientesForContactoId;
    }
   
    public Integer getEntidadNegocioId() {
        return this.entidadNegocioId;
    }
    
    public void setEntidadNegocioId(Integer entidadNegocioId) {
        this.entidadNegocioId = entidadNegocioId;
    }
    public PersonaTipoentidad getPersonaTipoentidad() {
        return this.personaTipoentidad;
    }
    
    public void setPersonaTipoentidad(PersonaTipoentidad personaTipoentidad) {
        this.personaTipoentidad = personaTipoentidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Date getFechaCese() {
        return this.fechaCese;
    }
    
    public void setFechaCese(Date fechaCese) {
        this.fechaCese = fechaCese;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public PersonaPersona getPersonaPersona() {
        return this.personaPersona;
    }
    
    public void setPersonaPersona(PersonaPersona personaPersona) {
        this.personaPersona = personaPersona;
    }
    public OrganizacionOrganizacion getOrganizacionOrganizacion() {
        return this.organizacionOrganizacion;
    }
    
    public void setOrganizacionOrganizacion(OrganizacionOrganizacion organizacionOrganizacion) {
        this.organizacionOrganizacion = organizacionOrganizacion;
    }
    public Set getPersonaDocumentoentidads() {
        return this.personaDocumentoentidads;
    }
    
    public void setPersonaDocumentoentidads(Set personaDocumentoentidads) {
        this.personaDocumentoentidads = personaDocumentoentidads;
    }
    public OrganizacionProveedor getOrganizacionProveedorByEntidadNegocioId() {
        return this.organizacionProveedorByEntidadNegocioId;
    }
    
    public void setOrganizacionProveedorByEntidadNegocioId(OrganizacionProveedor organizacionProveedorByEntidadNegocioId) {
        this.organizacionProveedorByEntidadNegocioId = organizacionProveedorByEntidadNegocioId;
    }
    public Set getOrganizacionClientesForEntidadNegocioId() {
        return this.organizacionClientesForEntidadNegocioId;
    }
    
    public void setOrganizacionClientesForEntidadNegocioId(Set organizacionClientesForEntidadNegocioId) {
        this.organizacionClientesForEntidadNegocioId = organizacionClientesForEntidadNegocioId;
    }
    public Set getPersonaDireccionentidads() {
        return this.personaDireccionentidads;
    }
    
    public void setPersonaDireccionentidads(Set personaDireccionentidads) {
        this.personaDireccionentidads = personaDireccionentidads;
    }
    public Set getOrganizacionProveedorsForContactoId() {
        return this.organizacionProveedorsForContactoId;
    }
    
    public void setOrganizacionProveedorsForContactoId(Set organizacionProveedorsForContactoId) {
        this.organizacionProveedorsForContactoId = organizacionProveedorsForContactoId;
    }
    public Set getOrganizacionClientesForContactoId() {
        return this.organizacionClientesForContactoId;
    }
    
    public void setOrganizacionClientesForContactoId(Set organizacionClientesForContactoId) {
        this.organizacionClientesForContactoId = organizacionClientesForContactoId;
    }




}


