package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PersonaDocumentoentidad generated by hbm2java
 */
public class PersonaDocumentoentidad  implements java.io.Serializable {


     private Integer documentoEntidadId;
     private PersonaEntidadnegocio personaEntidadnegocio;
     private PersonaTipodocumento personaTipodocumento;
     private String nombre;
     private String descripcion;
     private String observaion;
     private String ruta;
     private String extension;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;

    public PersonaDocumentoentidad() {
    }

	
    public PersonaDocumentoentidad(PersonaEntidadnegocio personaEntidadnegocio, PersonaTipodocumento personaTipodocumento, String nombre, String descripcion, String observaion, String ruta, String extension, Date fechaCreacion, boolean estadoRegistro) {
        this.personaEntidadnegocio = personaEntidadnegocio;
        this.personaTipodocumento = personaTipodocumento;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.observaion = observaion;
        this.ruta = ruta;
        this.extension = extension;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public PersonaDocumentoentidad(PersonaEntidadnegocio personaEntidadnegocio, PersonaTipodocumento personaTipodocumento, String nombre, String descripcion, String observaion, String ruta, String extension, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro) {
       this.personaEntidadnegocio = personaEntidadnegocio;
       this.personaTipodocumento = personaTipodocumento;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.observaion = observaion;
       this.ruta = ruta;
       this.extension = extension;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Integer getDocumentoEntidadId() {
        return this.documentoEntidadId;
    }
    
    public void setDocumentoEntidadId(Integer documentoEntidadId) {
        this.documentoEntidadId = documentoEntidadId;
    }
    public PersonaEntidadnegocio getPersonaEntidadnegocio() {
        return this.personaEntidadnegocio;
    }
    
    public void setPersonaEntidadnegocio(PersonaEntidadnegocio personaEntidadnegocio) {
        this.personaEntidadnegocio = personaEntidadnegocio;
    }
    public PersonaTipodocumento getPersonaTipodocumento() {
        return this.personaTipodocumento;
    }
    
    public void setPersonaTipodocumento(PersonaTipodocumento personaTipodocumento) {
        this.personaTipodocumento = personaTipodocumento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObservaion() {
        return this.observaion;
    }
    
    public void setObservaion(String observaion) {
        this.observaion = observaion;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


