package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PersonaTipodocumento generated by hbm2java
 */
public class PersonaTipodocumento  implements java.io.Serializable {


     private Integer tipoDocumentoId;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;
     private Set personaDocumentoentidads = new HashSet(0);

    public PersonaTipodocumento() {
    }

	
    public PersonaTipodocumento(String nombre, String descripcion, String abreviacion, Date fechaCreacion, boolean estadoRegistro) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public PersonaTipodocumento(String nombre, String descripcion, String abreviacion, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, Set personaDocumentoentidads) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.personaDocumentoentidads = personaDocumentoentidads;
    }
   
    public Integer getTipoDocumentoId() {
        return this.tipoDocumentoId;
    }
    
    public void setTipoDocumentoId(Integer tipoDocumentoId) {
        this.tipoDocumentoId = tipoDocumentoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getPersonaDocumentoentidads() {
        return this.personaDocumentoentidads;
    }
    
    public void setPersonaDocumentoentidads(Set personaDocumentoentidads) {
        this.personaDocumentoentidads = personaDocumentoentidads;
    }




}


