package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PersonaTipoentidad generated by hbm2java
 */
public class PersonaTipoentidad  implements java.io.Serializable {


     private Integer tipoEntidadId;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;
     private Set personaEntidadnegocios = new HashSet(0);

    public PersonaTipoentidad() {
    }

	
    public PersonaTipoentidad(String nombre, String descripcion, String abreviacion, Date fechaCreacion, boolean estadoRegistro) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public PersonaTipoentidad(String nombre, String descripcion, String abreviacion, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, Set personaEntidadnegocios) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.personaEntidadnegocios = personaEntidadnegocios;
    }
   
    public Integer getTipoEntidadId() {
        return this.tipoEntidadId;
    }
    
    public void setTipoEntidadId(Integer tipoEntidadId) {
        this.tipoEntidadId = tipoEntidadId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getPersonaEntidadnegocios() {
        return this.personaEntidadnegocios;
    }
    
    public void setPersonaEntidadnegocios(Set personaEntidadnegocios) {
        this.personaEntidadnegocios = personaEntidadnegocios;
    }




}


