package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PersonaDireccionentidad generated by hbm2java
 */
public class PersonaDireccionentidad  implements java.io.Serializable {


     private Integer direccionEntidadId;
     private LogisticaDistrito logisticaDistrito;
     private LogisticaTipodireccion logisticaTipodireccion;
     private LogisticaUsodireccion logisticaUsodireccion;
     private PersonaEntidadnegocio personaEntidadnegocio;
     private String nombre;
     private String descripcion;
     private long latitud;
     private long longitud;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private boolean estadoRegistro;
     private Set logisticaLocacions = new HashSet(0);

    public PersonaDireccionentidad() {
    }

	
    public PersonaDireccionentidad(LogisticaDistrito logisticaDistrito, LogisticaTipodireccion logisticaTipodireccion, LogisticaUsodireccion logisticaUsodireccion, PersonaEntidadnegocio personaEntidadnegocio, String nombre, String descripcion, long latitud, long longitud, Date fechaCreacion, boolean estadoRegistro) {
        this.logisticaDistrito = logisticaDistrito;
        this.logisticaTipodireccion = logisticaTipodireccion;
        this.logisticaUsodireccion = logisticaUsodireccion;
        this.personaEntidadnegocio = personaEntidadnegocio;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.latitud = latitud;
        this.longitud = longitud;
        this.fechaCreacion = fechaCreacion;
        this.estadoRegistro = estadoRegistro;
    }
    public PersonaDireccionentidad(LogisticaDistrito logisticaDistrito, LogisticaTipodireccion logisticaTipodireccion, LogisticaUsodireccion logisticaUsodireccion, PersonaEntidadnegocio personaEntidadnegocio, String nombre, String descripcion, long latitud, long longitud, Date fechaCreacion, Date fechaModificacion, boolean estadoRegistro, Set logisticaLocacions) {
       this.logisticaDistrito = logisticaDistrito;
       this.logisticaTipodireccion = logisticaTipodireccion;
       this.logisticaUsodireccion = logisticaUsodireccion;
       this.personaEntidadnegocio = personaEntidadnegocio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.latitud = latitud;
       this.longitud = longitud;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estadoRegistro = estadoRegistro;
       this.logisticaLocacions = logisticaLocacions;
    }
   
    public Integer getDireccionEntidadId() {
        return this.direccionEntidadId;
    }
    
    public void setDireccionEntidadId(Integer direccionEntidadId) {
        this.direccionEntidadId = direccionEntidadId;
    }
    public LogisticaDistrito getLogisticaDistrito() {
        return this.logisticaDistrito;
    }
    
    public void setLogisticaDistrito(LogisticaDistrito logisticaDistrito) {
        this.logisticaDistrito = logisticaDistrito;
    }
    public LogisticaTipodireccion getLogisticaTipodireccion() {
        return this.logisticaTipodireccion;
    }
    
    public void setLogisticaTipodireccion(LogisticaTipodireccion logisticaTipodireccion) {
        this.logisticaTipodireccion = logisticaTipodireccion;
    }
    public LogisticaUsodireccion getLogisticaUsodireccion() {
        return this.logisticaUsodireccion;
    }
    
    public void setLogisticaUsodireccion(LogisticaUsodireccion logisticaUsodireccion) {
        this.logisticaUsodireccion = logisticaUsodireccion;
    }
    public PersonaEntidadnegocio getPersonaEntidadnegocio() {
        return this.personaEntidadnegocio;
    }
    
    public void setPersonaEntidadnegocio(PersonaEntidadnegocio personaEntidadnegocio) {
        this.personaEntidadnegocio = personaEntidadnegocio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public long getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(long latitud) {
        this.latitud = latitud;
    }
    public long getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(long longitud) {
        this.longitud = longitud;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getLogisticaLocacions() {
        return this.logisticaLocacions;
    }
    
    public void setLogisticaLocacions(Set logisticaLocacions) {
        this.logisticaLocacions = logisticaLocacions;
    }




}


