package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductoResponsableactivo generated by hbm2java
 */
public class ProductoResponsableactivo  implements java.io.Serializable {


     private Integer responsableActivoId;
     private GeneralEstado generalEstado;
     private OrganizacionTrabajador organizacionTrabajador;
     private ProductoActivo productoActivo;
     private Date fechaInicio;
     private Date fechaFin;
     private String descripcion;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;

    public ProductoResponsableactivo() {
    }

    public ProductoResponsableactivo(GeneralEstado generalEstado, OrganizacionTrabajador organizacionTrabajador, ProductoActivo productoActivo, Date fechaInicio, Date fechaFin, String descripcion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
       this.generalEstado = generalEstado;
       this.organizacionTrabajador = organizacionTrabajador;
       this.productoActivo = productoActivo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.descripcion = descripcion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Integer getResponsableActivoId() {
        return this.responsableActivoId;
    }
    
    public void setResponsableActivoId(Integer responsableActivoId) {
        this.responsableActivoId = responsableActivoId;
    }
    public GeneralEstado getGeneralEstado() {
        return this.generalEstado;
    }
    
    public void setGeneralEstado(GeneralEstado generalEstado) {
        this.generalEstado = generalEstado;
    }
    public OrganizacionTrabajador getOrganizacionTrabajador() {
        return this.organizacionTrabajador;
    }
    
    public void setOrganizacionTrabajador(OrganizacionTrabajador organizacionTrabajador) {
        this.organizacionTrabajador = organizacionTrabajador;
    }
    public ProductoActivo getProductoActivo() {
        return this.productoActivo;
    }
    
    public void setProductoActivo(ProductoActivo productoActivo) {
        this.productoActivo = productoActivo;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


