package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductoModelo generated by hbm2java
 */
public class ProductoModelo  implements java.io.Serializable {


     private Integer modeloId;
     private ProductoMarca productoMarca;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;
     private Set productoSeries = new HashSet(0);
     private Set productoProductos = new HashSet(0);

    public ProductoModelo() {
    }

	
    public ProductoModelo(ProductoMarca productoMarca, String nombre, String descripcion, String abreviacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
        this.productoMarca = productoMarca;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.fechaModificacion = fechaModificacion;
        this.usuarioModificacion = usuarioModificacion;
        this.estadoRegistro = estadoRegistro;
    }
    public ProductoModelo(ProductoMarca productoMarca, String nombre, String descripcion, String abreviacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro, Set productoSeries, Set productoProductos) {
       this.productoMarca = productoMarca;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
       this.productoSeries = productoSeries;
       this.productoProductos = productoProductos;
    }
   
    public Integer getModeloId() {
        return this.modeloId;
    }
    
    public void setModeloId(Integer modeloId) {
        this.modeloId = modeloId;
    }
    public ProductoMarca getProductoMarca() {
        return this.productoMarca;
    }
    
    public void setProductoMarca(ProductoMarca productoMarca) {
        this.productoMarca = productoMarca;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getProductoSeries() {
        return this.productoSeries;
    }
    
    public void setProductoSeries(Set productoSeries) {
        this.productoSeries = productoSeries;
    }
    public Set getProductoProductos() {
        return this.productoProductos;
    }
    
    public void setProductoProductos(Set productoProductos) {
        this.productoProductos = productoProductos;
    }




}


