package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductoRelacionproducto generated by hbm2java
 */
public class ProductoRelacionproducto  implements java.io.Serializable {


     private Integer relacionProductoId;
     private GeneralEstado generalEstado;
     private ProductoProducto productoProductoByProductoOrigenId;
     private ProductoProducto productoProductoByProductoDestinoId;
     private ProductoTiporelacion productoTiporelacion;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;

    public ProductoRelacionproducto() {
    }

    public ProductoRelacionproducto(GeneralEstado generalEstado, ProductoProducto productoProductoByProductoOrigenId, ProductoProducto productoProductoByProductoDestinoId, ProductoTiporelacion productoTiporelacion, String descripcion, Date fechaInicio, Date fechaFin, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
       this.generalEstado = generalEstado;
       this.productoProductoByProductoOrigenId = productoProductoByProductoOrigenId;
       this.productoProductoByProductoDestinoId = productoProductoByProductoDestinoId;
       this.productoTiporelacion = productoTiporelacion;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Integer getRelacionProductoId() {
        return this.relacionProductoId;
    }
    
    public void setRelacionProductoId(Integer relacionProductoId) {
        this.relacionProductoId = relacionProductoId;
    }
    public GeneralEstado getGeneralEstado() {
        return this.generalEstado;
    }
    
    public void setGeneralEstado(GeneralEstado generalEstado) {
        this.generalEstado = generalEstado;
    }
    public ProductoProducto getProductoProductoByProductoOrigenId() {
        return this.productoProductoByProductoOrigenId;
    }
    
    public void setProductoProductoByProductoOrigenId(ProductoProducto productoProductoByProductoOrigenId) {
        this.productoProductoByProductoOrigenId = productoProductoByProductoOrigenId;
    }
    public ProductoProducto getProductoProductoByProductoDestinoId() {
        return this.productoProductoByProductoDestinoId;
    }
    
    public void setProductoProductoByProductoDestinoId(ProductoProducto productoProductoByProductoDestinoId) {
        this.productoProductoByProductoDestinoId = productoProductoByProductoDestinoId;
    }
    public ProductoTiporelacion getProductoTiporelacion() {
        return this.productoTiporelacion;
    }
    
    public void setProductoTiporelacion(ProductoTiporelacion productoTiporelacion) {
        this.productoTiporelacion = productoTiporelacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


