package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductoProducto generated by hbm2java
 */
public class ProductoProducto  implements java.io.Serializable {


     private Integer productoId;
     private GeneralEstado generalEstado;
     private OrganizacionOrganizacion organizacionOrganizacion;
     private OrganizacionProveedor organizacionProveedor;
     private ProductoMarca productoMarca;
     private ProductoModelo productoModelo;
     private ProductoSerie productoSerie;
     private ProductoTipoproducto productoTipoproducto;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private String codigo;
     private Date fechaAdquisicion;
     private String documentoAdquisicion;
     private String documentoRequerimiento;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;
     private Set productoProductoatributos = new HashSet(0);
     private Set productoInventarios = new HashSet(0);
     private Set productoRelacionproductosForProductoOrigenId = new HashSet(0);
     private Set productoActivos = new HashSet(0);
     private Set productoRelacionproductosForProductoDestinoId = new HashSet(0);

    public ProductoProducto() {
    }

	
    public ProductoProducto(GeneralEstado generalEstado, OrganizacionOrganizacion organizacionOrganizacion, OrganizacionProveedor organizacionProveedor, ProductoMarca productoMarca, ProductoModelo productoModelo, ProductoSerie productoSerie, ProductoTipoproducto productoTipoproducto, String nombre, String descripcion, String abreviacion, String codigo, Date fechaAdquisicion, String documentoAdquisicion, String documentoRequerimiento, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
        this.generalEstado = generalEstado;
        this.organizacionOrganizacion = organizacionOrganizacion;
        this.organizacionProveedor = organizacionProveedor;
        this.productoMarca = productoMarca;
        this.productoModelo = productoModelo;
        this.productoSerie = productoSerie;
        this.productoTipoproducto = productoTipoproducto;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.codigo = codigo;
        this.fechaAdquisicion = fechaAdquisicion;
        this.documentoAdquisicion = documentoAdquisicion;
        this.documentoRequerimiento = documentoRequerimiento;
        this.fechaModificacion = fechaModificacion;
        this.usuarioModificacion = usuarioModificacion;
        this.estadoRegistro = estadoRegistro;
    }
    public ProductoProducto(GeneralEstado generalEstado, OrganizacionOrganizacion organizacionOrganizacion, OrganizacionProveedor organizacionProveedor, ProductoMarca productoMarca, ProductoModelo productoModelo, ProductoSerie productoSerie, ProductoTipoproducto productoTipoproducto, String nombre, String descripcion, String abreviacion, String codigo, Date fechaAdquisicion, String documentoAdquisicion, String documentoRequerimiento, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro, Set productoProductoatributos, Set productoInventarios, Set productoRelacionproductosForProductoOrigenId, Set productoActivos, Set productoRelacionproductosForProductoDestinoId) {
       this.generalEstado = generalEstado;
       this.organizacionOrganizacion = organizacionOrganizacion;
       this.organizacionProveedor = organizacionProveedor;
       this.productoMarca = productoMarca;
       this.productoModelo = productoModelo;
       this.productoSerie = productoSerie;
       this.productoTipoproducto = productoTipoproducto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.codigo = codigo;
       this.fechaAdquisicion = fechaAdquisicion;
       this.documentoAdquisicion = documentoAdquisicion;
       this.documentoRequerimiento = documentoRequerimiento;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
       this.productoProductoatributos = productoProductoatributos;
       this.productoInventarios = productoInventarios;
       this.productoRelacionproductosForProductoOrigenId = productoRelacionproductosForProductoOrigenId;
       this.productoActivos = productoActivos;
       this.productoRelacionproductosForProductoDestinoId = productoRelacionproductosForProductoDestinoId;
    }
   
    public Integer getProductoId() {
        return this.productoId;
    }
    
    public void setProductoId(Integer productoId) {
        this.productoId = productoId;
    }
    public GeneralEstado getGeneralEstado() {
        return this.generalEstado;
    }
    
    public void setGeneralEstado(GeneralEstado generalEstado) {
        this.generalEstado = generalEstado;
    }
    public OrganizacionOrganizacion getOrganizacionOrganizacion() {
        return this.organizacionOrganizacion;
    }
    
    public void setOrganizacionOrganizacion(OrganizacionOrganizacion organizacionOrganizacion) {
        this.organizacionOrganizacion = organizacionOrganizacion;
    }
    public OrganizacionProveedor getOrganizacionProveedor() {
        return this.organizacionProveedor;
    }
    
    public void setOrganizacionProveedor(OrganizacionProveedor organizacionProveedor) {
        this.organizacionProveedor = organizacionProveedor;
    }
    public ProductoMarca getProductoMarca() {
        return this.productoMarca;
    }
    
    public void setProductoMarca(ProductoMarca productoMarca) {
        this.productoMarca = productoMarca;
    }
    public ProductoModelo getProductoModelo() {
        return this.productoModelo;
    }
    
    public void setProductoModelo(ProductoModelo productoModelo) {
        this.productoModelo = productoModelo;
    }
    public ProductoSerie getProductoSerie() {
        return this.productoSerie;
    }
    
    public void setProductoSerie(ProductoSerie productoSerie) {
        this.productoSerie = productoSerie;
    }
    public ProductoTipoproducto getProductoTipoproducto() {
        return this.productoTipoproducto;
    }
    
    public void setProductoTipoproducto(ProductoTipoproducto productoTipoproducto) {
        this.productoTipoproducto = productoTipoproducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFechaAdquisicion() {
        return this.fechaAdquisicion;
    }
    
    public void setFechaAdquisicion(Date fechaAdquisicion) {
        this.fechaAdquisicion = fechaAdquisicion;
    }
    public String getDocumentoAdquisicion() {
        return this.documentoAdquisicion;
    }
    
    public void setDocumentoAdquisicion(String documentoAdquisicion) {
        this.documentoAdquisicion = documentoAdquisicion;
    }
    public String getDocumentoRequerimiento() {
        return this.documentoRequerimiento;
    }
    
    public void setDocumentoRequerimiento(String documentoRequerimiento) {
        this.documentoRequerimiento = documentoRequerimiento;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getProductoProductoatributos() {
        return this.productoProductoatributos;
    }
    
    public void setProductoProductoatributos(Set productoProductoatributos) {
        this.productoProductoatributos = productoProductoatributos;
    }
    public Set getProductoInventarios() {
        return this.productoInventarios;
    }
    
    public void setProductoInventarios(Set productoInventarios) {
        this.productoInventarios = productoInventarios;
    }
    public Set getProductoRelacionproductosForProductoOrigenId() {
        return this.productoRelacionproductosForProductoOrigenId;
    }
    
    public void setProductoRelacionproductosForProductoOrigenId(Set productoRelacionproductosForProductoOrigenId) {
        this.productoRelacionproductosForProductoOrigenId = productoRelacionproductosForProductoOrigenId;
    }
    public Set getProductoActivos() {
        return this.productoActivos;
    }
    
    public void setProductoActivos(Set productoActivos) {
        this.productoActivos = productoActivos;
    }
    public Set getProductoRelacionproductosForProductoDestinoId() {
        return this.productoRelacionproductosForProductoDestinoId;
    }
    
    public void setProductoRelacionproductosForProductoDestinoId(Set productoRelacionproductosForProductoDestinoId) {
        this.productoRelacionproductosForProductoDestinoId = productoRelacionproductosForProductoDestinoId;
    }




}


