package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductoProductoatributo generated by hbm2java
 */
public class ProductoProductoatributo  implements java.io.Serializable {


     private Integer productoAtributoId;
     private GeneralEstado generalEstado;
     private ProductoAtributo productoAtributo;
     private ProductoProducto productoProducto;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private Date fechaActualizacion;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;

    public ProductoProductoatributo() {
    }

    public ProductoProductoatributo(GeneralEstado generalEstado, ProductoAtributo productoAtributo, ProductoProducto productoProducto, String nombre, String descripcion, String abreviacion, Date fechaActualizacion, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
       this.generalEstado = generalEstado;
       this.productoAtributo = productoAtributo;
       this.productoProducto = productoProducto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.fechaActualizacion = fechaActualizacion;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Integer getProductoAtributoId() {
        return this.productoAtributoId;
    }
    
    public void setProductoAtributoId(Integer productoAtributoId) {
        this.productoAtributoId = productoAtributoId;
    }
    public GeneralEstado getGeneralEstado() {
        return this.generalEstado;
    }
    
    public void setGeneralEstado(GeneralEstado generalEstado) {
        this.generalEstado = generalEstado;
    }
    public ProductoAtributo getProductoAtributo() {
        return this.productoAtributo;
    }
    
    public void setProductoAtributo(ProductoAtributo productoAtributo) {
        this.productoAtributo = productoAtributo;
    }
    public ProductoProducto getProductoProducto() {
        return this.productoProducto;
    }
    
    public void setProductoProducto(ProductoProducto productoProducto) {
        this.productoProducto = productoProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


