package org.primefaces.omega.modelo;
// Generated 30-may-2017 1:23:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductoCategoria generated by hbm2java
 */
public class ProductoCategoria  implements java.io.Serializable {


     private Integer categoriaId;
     private ProductoCategoria productoCategoria;
     private String nombre;
     private String descripcion;
     private String abreviacion;
     private int nivel;
     private boolean activo;
     private Date fechaModificacion;
     private String usuarioModificacion;
     private boolean estadoRegistro;
     private Set productoCategorias = new HashSet(0);

    public ProductoCategoria() {
    }

	
    public ProductoCategoria(ProductoCategoria productoCategoria, String nombre, String descripcion, String abreviacion, int nivel, boolean activo, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro) {
        this.productoCategoria = productoCategoria;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.abreviacion = abreviacion;
        this.nivel = nivel;
        this.activo = activo;
        this.fechaModificacion = fechaModificacion;
        this.usuarioModificacion = usuarioModificacion;
        this.estadoRegistro = estadoRegistro;
    }
    public ProductoCategoria(ProductoCategoria productoCategoria, String nombre, String descripcion, String abreviacion, int nivel, boolean activo, Date fechaModificacion, String usuarioModificacion, boolean estadoRegistro, Set productoCategorias) {
       this.productoCategoria = productoCategoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.abreviacion = abreviacion;
       this.nivel = nivel;
       this.activo = activo;
       this.fechaModificacion = fechaModificacion;
       this.usuarioModificacion = usuarioModificacion;
       this.estadoRegistro = estadoRegistro;
       this.productoCategorias = productoCategorias;
    }
   
    public Integer getCategoriaId() {
        return this.categoriaId;
    }
    
    public void setCategoriaId(Integer categoriaId) {
        this.categoriaId = categoriaId;
    }
    public ProductoCategoria getProductoCategoria() {
        return this.productoCategoria;
    }
    
    public void setProductoCategoria(ProductoCategoria productoCategoria) {
        this.productoCategoria = productoCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    public boolean isEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(boolean estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set getProductoCategorias() {
        return this.productoCategorias;
    }
    
    public void setProductoCategorias(Set productoCategorias) {
        this.productoCategorias = productoCategorias;
    }




}


